### ISSUE TITLE
Buffer size not enough if reading at high rate

### ISSUE THREAD

**Issue by coderdj** [coderdj/redax#34]
I think this happens when you're pulling data in faster than you're clearing. 

So what we can do to go around that is instead of writing to a large, monolithic buffer, we just declare an array of buffers each with one BLT size. Then dynamically append to this array. Then copy them to one buffer in the copy stage, which is performed anyway.

**Comment by darrylmasson** [comment]
Pretty sure this got issue was resolved quite some commits ago.
