### ISSUE TITLE
Dispatcher gets caught in arm-stop loops

### ISSUE THREAD

**Issue by darrylmasson** [coderdj/redax#63]
Because of the delay between when stop commands are issued to the CC and the readers, the dispatcher can get caught in a loop where arm commands get scheduled between these stop commands.

**Comment by AlexElykov** [comment]
I've reduced the delay to 2 sec and ran with it for a while, it's also the currently used value in the dispatcher on reader0. However, there are issues with the m_veto, so I'm not sure if this is the "correct" value.

**Comment by darrylmasson** [comment]
If we set the value too short, redax doesn't have time to clear the boards and process the remaining data before its stop command comes through. It's better to increase the delay to the stop commands.
