### ISSUE TITLE
Read SN register error for certain boards on reader5

### ISSUE THREAD

**Issue by AlexElykov** [coderdj/redax#65]
https://github.com/coderdj/redax/blob/9d9b61fd544deb230eedb031665de90159c37a58/V1724.cc#L120

https://github.com/coderdj/redax/blob/9d9b61fd544deb230eedb031665de90159c37a58/V1724.cc#L125
Seem to generate an error in some boards during init e.g. "Board 907 read returned: -2 (ret) 0x55823570 (val) for reg 0xf080". Removing these calls allows everything to initialize properly (at least it seems so).

**Comment by darrylmasson** [comment]
PR #69 introduces a config option to bypass the serial number check. This doesn't solve the problem but it does address the symptoms.

**Comment by AlexElykov** [comment]
Alright will check it with the muon veto next week.
